name: Building app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_upload:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Step 1 - Creating build directory
      run: mkdir build
    - name: Step 2 - Generating makefile
      run: ${{ github.workspace }}\mingw_64\bin\qmake.exe -makefile ${{ github.workspace }}\src\Ex1.pro
      working-directory: build
    - name: Step 3 - Building binary
      run: make
      working-directory: build
    - name: Step 4 - Building windows deployement
      run: |
        echo "${{ github.workspace }}\mingw_64\bin" >> $GITHUB_PATH
        ${{ github.workspace }}\mingw_64\bin\windeployqt.exe .
      working-directory: build
    - name: Step 5 - Uploading artifact
      uses: actions/upload-artifact@v3.1.2
      with: 
        name: Brick_Breaker
        path: build
        retention-days: 1
  download:
    runs-on: windows-latest
    needs: build_and_upload
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.2
        with:
          # Artifact name
          name: Brick_Breaker
