name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Step 1 - Creating build directory
      run: mkdir build
    - name: Step 2 - Generating makefile
      run: ${{ github.workspace }}\mingw_64\bin\qmake.exe -makefile ${{ github.workspace }}\src\Ex1.pro
      working-directory: build
    - name: Step 3 - Building binary
      run: make
      working-directory: build
    - name: Step 4 - Uploading artifact
      uses: actions/upload-artifact@v3.1.2
      with: 
        name: Brick_Breaker
        path: build
        retention-days: 1
