name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Building-Qt:
    runs-on: windows-lastest
    steps:
    - uses: actions/checkout@v3
    - name: Step 1 - Cloning Git
      run: git clone git://code.qt.io/qt/qt5.git qt6
    - name: Step 2 - Configuring Git
      run: git switch v6.5.0
      working-directory: qt6
    - name: Step 3 - Fetching sub-modules
      run: perl init-repository
      working-directory: qt6
    - name: Step 4 - Building Qt6.5.0
      run: | 
        mkdir qt6-build
        cd qt6-build
        ..\qt6\configure.bat -prefix ${{ github.workspace }}\Qt6.5.0
        cmake --build .
        cmake --install .
  build_and_upload:
    runs-on: windows-latest
    needs: Building-Qt
    steps:
    - uses: actions/checkout@v3
    - name: Step 1 - Creating build directory
      run: mkdir build
    - name: Step 2 - Generating makefile
      run: ${{ github.workspace }}\mingw_64\bin\qmake.exe -makefile ${{ github.workspace }}\src\Ex1.pro
      working-directory: build
    - name: Step 3 - Building binary
      run: make
      working-directory: build
    - name: Step 4 - Uploading artifact
      uses: actions/upload-artifact@v3.1.2
      with: 
        name: Brick_Breaker
        path: build
        retention-days: 1
  download:
    runs-on: windows-latest
    needs: build_and_upload
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.2
        with:
          # Artifact name
          name: Brick_Breaker
