name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make Ex1.pro
      run: make Ex1.pro
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
