name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Step 1 - Building binary
      run: make Ex1.pro
    - name: Step 2 - Uploading artifact
      uses: actions/upload-artifact@v3.1.2
      with: 
        name: Brick_Breaker
        path: .
